//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int PId { get; set; }
        public decimal Price { get; set; }
        public string PName { get; set; }
        public string PImage { get; set; }
        public string PCategory { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
